import { c as create_ssr_component, a as escape } from "./ssr.js";
const css = {
  code: '#subheader.svelte-11ytay3.svelte-11ytay3{background:#000;display:flex;justify-content:center;align-items:flex-end;padding:8em 0 2em;position:relative;isolation:isolate}@media only screen and (min-width: 768px){#subheader.svelte-11ytay3.svelte-11ytay3{text-align:left;padding:0 0 3em 0;height:18.65em}}#subheader.svelte-11ytay3.svelte-11ytay3::before{content:"";width:100%;height:100%;position:absolute;top:0;left:0;z-index:-1;background:linear-gradient(90.01deg, #27631a 16.86%, rgba(0, 0, 0, 0) 100%)}#subheader.svelte-11ytay3 .container.svelte-11ytay3{text-align:center;width:96%;max-width:60em;margin:0 auto}@media only screen and (min-width: 768px){#subheader.svelte-11ytay3 .container.svelte-11ytay3{text-align:left}}#subheader.svelte-11ytay3 h1.svelte-11ytay3{color:white;font-weight:bold;font-size:2.45em;margin-bottom:0}',
  map: '{"version":3,"file":"SubNavigation.svelte","sources":["SubNavigation.svelte"],"sourcesContent":["<script lang=\\"ts\\">export let pageTitle;\\n<\/script>\\n\\n<section id=\\"subheader\\">\\n  <div class=\\"container\\">\\n    <h1>{pageTitle}</h1>\\n  </div>\\n</section>\\n\\n<style lang=\\"less\\">#subheader {\\n  background: #000;\\n  display: flex;\\n  justify-content: center;\\n  align-items: flex-end;\\n  padding: 8em 0 2em;\\n  position: relative;\\n  isolation: isolate;\\n}\\n@media only screen and (min-width: 768px) {\\n  #subheader {\\n    text-align: left;\\n    padding: 0 0 3em 0;\\n    height: 18.65em;\\n  }\\n}\\n#subheader::before {\\n  content: \\"\\";\\n  width: 100%;\\n  height: 100%;\\n  position: absolute;\\n  top: 0;\\n  left: 0;\\n  z-index: -1;\\n  background: linear-gradient(90.01deg, #27631a 16.86%, rgba(0, 0, 0, 0) 100%);\\n}\\n#subheader .container {\\n  text-align: center;\\n  width: 96%;\\n  max-width: 60em;\\n  margin: 0 auto;\\n}\\n@media only screen and (min-width: 768px) {\\n  #subheader .container {\\n    text-align: left;\\n  }\\n}\\n#subheader h1 {\\n  color: white;\\n  font-weight: bold;\\n  font-size: 2.45em;\\n  margin-bottom: 0;\\n}\\n</style>\\n"],"names":[],"mappings":"AASmB,wCAAW,CAC5B,UAAU,CAAE,IAAI,CAChB,OAAO,CAAE,IAAI,CACb,eAAe,CAAE,MAAM,CACvB,WAAW,CAAE,QAAQ,CACrB,OAAO,CAAE,GAAG,CAAC,CAAC,CAAC,GAAG,CAClB,QAAQ,CAAE,QAAQ,CAClB,SAAS,CAAE,OACb,CACA,OAAO,IAAI,CAAC,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAE,CACxC,wCAAW,CACT,UAAU,CAAE,IAAI,CAChB,OAAO,CAAE,CAAC,CAAC,CAAC,CAAC,GAAG,CAAC,CAAC,CAClB,MAAM,CAAE,OACV,CACF,CACA,wCAAU,QAAS,CACjB,OAAO,CAAE,EAAE,CACX,KAAK,CAAE,IAAI,CACX,MAAM,CAAE,IAAI,CACZ,QAAQ,CAAE,QAAQ,CAClB,GAAG,CAAE,CAAC,CACN,IAAI,CAAE,CAAC,CACP,OAAO,CAAE,EAAE,CACX,UAAU,CAAE,gBAAgB,QAAQ,CAAC,CAAC,OAAO,CAAC,MAAM,CAAC,CAAC,KAAK,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,CAAC,IAAI,CAC7E,CACA,yBAAU,CAAC,yBAAW,CACpB,UAAU,CAAE,MAAM,CAClB,KAAK,CAAE,GAAG,CACV,SAAS,CAAE,IAAI,CACf,MAAM,CAAE,CAAC,CAAC,IACZ,CACA,OAAO,IAAI,CAAC,MAAM,CAAC,GAAG,CAAC,YAAY,KAAK,CAAE,CACxC,yBAAU,CAAC,yBAAW,CACpB,UAAU,CAAE,IACd,CACF,CACA,yBAAU,CAAC,iBAAG,CACZ,KAAK,CAAE,KAAK,CACZ,WAAW,CAAE,IAAI,CACjB,SAAS,CAAE,MAAM,CACjB,aAAa,CAAE,CACjB"}'
};
const SubNavigation = create_ssr_component(($$result, $$props, $$bindings, slots) => {
  let { pageTitle } = $$props;
  if ($$props.pageTitle === void 0 && $$bindings.pageTitle && pageTitle !== void 0)
    $$bindings.pageTitle(pageTitle);
  $$result.css.add(css);
  return `<section id="subheader" class="svelte-11ytay3"><div class="container svelte-11ytay3"><h1 class="svelte-11ytay3">${escape(pageTitle)}</h1></div> </section>`;
});
export {
  SubNavigation as S
};
